name: HybridTrainer
options:
  bundleIdPrefix: com.nobelgirmay
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

targets:
  Models:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Models
    settings:
      base:
        INFOPLIST_FILE: Models/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nobelgirmay.HybridTrainer.Models
    info:
      path: Models/Info.plist
    dependencies:
      - sdk: SwiftUI.framework

  HybridTrainer:
    type: application
    platform: iOS
    sources:
      - path: Design
      - path: HybridTrainer
      - path: ViewModels
      - path: Views
      - path: Services
    settings:
      base:
        INFOPLIST_FILE: HybridTrainer/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nobelgirmay.HybridTrainer
    dependencies:
      - target: Models
      - sdk: SwiftUI.framework
      - sdk: HealthKit.framework
