name: HybridTrainer
options:
  bundleIdPrefix: com.nobelgirmay
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

targets:
  Models:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Models
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: HealthKit.framework
      - sdk: SwiftData.framework
    settings:
      base:
        ENABLE_TESTABILITY: YES
        DEFINES_MODULE: YES
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES

  HybridTrainer:
    type: application
    platform: iOS
    sources:
      - path: HybridTrainer
      - path: Views
      - path: Utilities
      - path: Services
      - path: .
        excludes:
          - "project.yml"
          - "README.md"
          - "LICENSE"
          - "Models"
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: HybridTrainer/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nobelgirmay.HybridTrainer
        DEVELOPMENT_TEAM: S84HXJP4K6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    dependencies:
      - target: Models
      - sdk: SwiftUI.framework
      - sdk: HealthKit.framework
      - sdk: SwiftData.framework
    info:
      path: HybridTrainer/Info.plist
      properties:
        NSHealthShareUsageDescription: "We need access to HealthKit to track your workouts"
        NSHealthUpdateUsageDescription: "We need access to HealthKit to save your workouts"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true

  HybridTrainerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HybridTrainerTests
    dependencies:
      - target: HybridTrainer

  HybridTrainerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: HybridTrainerUITests
    dependencies:
      - target: HybridTrainer
